#spring:
#  database: h2
#  console: true
#  path: /h2
#
#  datasource:
#    platform: h2
#    url: jdbc:h2://localhost:8099/h2
#    username: user
#    password: 123456
#    driverClassName: org.h2.Driver
#
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#    path: /h2
#    settings:
#      web-allow-others: false

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver