spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create


spring.freemarker.template-loader-path: /
spring.freemarker.suffix: .ftl